version: '2.6'
services:
  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    container_name: backend
    image: daneliyapavel/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    container_name: frontend
    image: daneliyapavel/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - frontend

volumes:
  postgres_data:
    name: postgres_data
  static_value:
      name: static_value
  media_value:
      name: media_value